import { chromium } from 'playwright';
const b = await chromium.launch();
let p = await b.newPage({ viewport: { width: 1440, height: 900 } });
await p.goto('http://localhost:4391/', { waitUntil: 'networkidle' });
await p.evaluate(() => document.querySelector('#schalen').scrollIntoView()); await p.waitForTimeout(400);
await p.mouse.wheel(0, 500); await p.waitForTimeout(3500);
const cells = await p.$$('.bowl'); await cells[40].hover(); await p.waitForTimeout(900);
await p.screenshot({ path: '.shots/r3-bowls-hover.jpg', quality: 75 });
await p.evaluate(() => document.querySelector('.scale').scrollIntoView({block:'center'})); await p.waitForTimeout(500);
const bands = await p.$$('.scale__band'); await bands[3].hover(); await p.waitForTimeout(1300);
await p.screenshot({ path: '.shots/r3-scale-hover.jpg', quality: 75 });
await p.evaluate(() => window.scrollTo(0, document.body.scrollHeight)); await p.waitForTimeout(800);
await p.screenshot({ path: '.shots/r3-footer.jpg', quality: 75 });
await p.close();
p = await b.newPage({ viewport: { width: 390, height: 844 } });
await p.goto('http://localhost:4391/', { waitUntil: 'networkidle' }); await p.waitForTimeout(800);
await p.click('[data-menu-toggle]'); await p.waitForTimeout(700);
await p.screenshot({ path: '.shots/r3-mobile-menu.jpg', quality: 75 });
await b.close();
