import { chromium } from 'playwright';
const b = await chromium.launch();
let p = await b.newPage({ viewport: { width: 1440, height: 900 } });
const errs = []; p.on('pageerror', e => errs.push(e.message)); p.on('console', m => m.type() === 'error' && errs.push(m.text()));
await p.goto('http://localhost:4391/manufaktur.html', { waitUntil: 'networkidle' }); await p.waitForTimeout(2500);
await p.screenshot({ path: '.shots/sub-manufaktur-confirm-hero.jpg', quality: 75 });
await p.evaluate(() => document.querySelector('#farben').scrollIntoView()); await p.waitForTimeout(1500);
const btns = await p.$$('.glaze__btn'); await btns[3].hover(); await p.waitForTimeout(1600);
await p.screenshot({ path: '.shots/sub-manufaktur-confirm-glaze.jpg', quality: 75 });
await p.evaluate(() => document.querySelector('#edition').scrollIntoView()); await p.mouse.wheel(0, 200); await p.waitForTimeout(2500);
await p.screenshot({ path: '.shots/sub-manufaktur-confirm-edition.jpg', quality: 75 });
await p.goto('http://localhost:4391/meisterstuecke.html#arbeitsweise', { waitUntil: 'networkidle' }); await p.mouse.wheel(0, 700); await p.waitForTimeout(2500);
await p.screenshot({ path: '.shots/sub-meisterstuecke-confirm-steps.jpg', quality: 75 });
await p.close();
p = await b.newPage({ viewport: { width: 390, height: 844 } });
p.on('pageerror', e => errs.push(e.message));
await p.goto('http://localhost:4391/manufaktur.html', { waitUntil: 'networkidle' });
await p.evaluate(() => document.querySelector('.glaze__pick').scrollIntoView({ block: 'end' })); await p.waitForTimeout(1500);
const mb = await p.$$('.glaze__btn'); await mb[5].tap?.() ?? await mb[5].click(); await mb[5].click(); await p.waitForTimeout(1500);
await p.screenshot({ path: '.shots/sub-manufaktur-confirm-mobile-glaze.jpg', quality: 75 });
console.log('errors', errs);
await b.close();
