/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type Werkstatt = {
  _id: string;
  _type: 'werkstatt';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  firma: string;
  strasse: string;
  plz: string;
  ort: string;
  adresszusatz?: string;
  telefon: string;
  email: string;
  oeffnungszeiten?: Array<{
    wochentage: string;
    von: string;
    bis: string;
    _type: 'zeitraum';
    _key: string;
  }>;
  hinweisZeiten?: string;
};

export type Seite = {
  _id: string;
  _type: 'seite';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  titel: string;
  einleitung?: string;
  beschreibung: string;
};

export type Hinweis = {
  _id: string;
  _type: 'hinweis';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  text: string;
  gueltigVon: string;
  gueltigBis: string;
  wichtig?: boolean;
};

export type OrtReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'ort';
};

export type GalerieReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'galerie';
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
};

export type Ausstellung = {
  _id: string;
  _type: 'ausstellung';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  titel: string;
  art: 'museum' | 'galerie' | 'werkstatt' | 'messe';
  start: string;
  ende: string;
  eroeffnung?: string;
  ort: OrtReference;
  galerie?: GalerieReference;
  haus: string;
  adresse?: string;
  oeffnungszeiten?: string;
  beschreibung?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal';
    listItem?: never;
    markDefs?: Array<{
      href: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
  hauptbild: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    nachweis: string;
    _type: 'image';
  };
  bilder?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    nachweis: string;
    _type: 'image';
    _key: string;
  }>;
  flyer?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: 'image';
  };
  link?: string;
  spotlight?: boolean;
};

export type SanityImageCrop = {
  _type: 'sanity.imageCrop';
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot';
  x: number;
  y: number;
  height: number;
  width: number;
};

export type Galerie = {
  _id: string;
  _type: 'galerie';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  stadt: string;
  adresse?: string;
  link?: string;
  vertretung?: boolean;
  vertretungSeit?: number;
};

export type Ort = {
  _id: string;
  _type: 'ort';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  stadt: string;
  land: string;
  kurztext?: string;
  bild?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: 'image';
  };
  reihenfolge?: number;
};

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch';
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: 'sanity.imagePalette';
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions';
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata';
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: 'sanity.fileAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData';
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: 'sanity.imageAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: 'geopoint';
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: 'slug';
  current: string;
  source?: string;
};

export type AllSanitySchemaTypes =
  | Werkstatt
  | Seite
  | Hinweis
  | OrtReference
  | GalerieReference
  | SanityImageAssetReference
  | Ausstellung
  | SanityImageCrop
  | SanityImageHotspot
  | Galerie
  | Ort
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint
  | Slug;
