/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type Werkstatt = {
  _id: string;
  _type: 'werkstatt';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  firma: string;
  strasse: string;
  plz: string;
  ort: string;
  adresszusatz?: string;
  telefon: string;
  email: string;
  englischeSeite?: string;
  nahverkehr?: string;
  oeffnungszeiten?: Array<{
    tagVon: 'Montag' | 'Dienstag' | 'Mittwoch' | 'Donnerstag' | 'Freitag' | 'Samstag' | 'Sonntag';
    tagBis?: 'Montag' | 'Dienstag' | 'Mittwoch' | 'Donnerstag' | 'Freitag' | 'Samstag' | 'Sonntag';
    von: string;
    bis: string;
    _type: 'zeitraum';
    _key: string;
  }>;
  hinweisZeiten?: string;
};

export type Seite = {
  _id: string;
  _type: 'seite';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  titel: string;
  einleitung?: string;
  beschreibung: string;
};

export type Hinweis = {
  _id: string;
  _type: 'hinweis';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  text: string;
  gueltigVon: string;
  gueltigBis: string;
  wichtig?: boolean;
};

export type OrtReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'ort';
};

export type GalerieReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'galerie';
};

export type ArchivEintrag = {
  _id: string;
  _type: 'archivEintrag';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  jahr: number;
  beginnJahr?: number;
  reihenfolge: number;
  inListe?: boolean;
  titel?: string;
  ortszeile?: string;
  datum?: string;
  link?: {
    text: string;
    url: string;
  };
  ort?: OrtReference;
  haus?: string;
  galerie?: GalerieReference;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
};

export type Ausstellung = {
  _id: string;
  _type: 'ausstellung';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  titel: string;
  art: 'museum' | 'kirche' | 'galerie' | 'werkstatt' | 'messe';
  start: string;
  ende: string;
  eroeffnung?: Array<string>;
  ort: OrtReference;
  galerie?: GalerieReference;
  haus: string;
  adresse?: Array<string>;
  oeffnungszeiten?: Array<string>;
  oeffnungszeitenBezeichnung?: string;
  kooperation?: Array<string>;
  beschreibung?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal';
    listItem?: never;
    markDefs?: Array<{
      href: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
  hauptbild: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    bildunterschrift?: string;
    nachweis: string;
    _type: 'image';
  };
  bilder?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    bildunterschrift?: string;
    nachweis: string;
    _type: 'image';
    _key: string;
  }>;
  flyer?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: 'image';
  };
  link?: {
    text: string;
    url: string;
  };
  spotlight?: boolean;
};

export type SanityImageCrop = {
  _type: 'sanity.imageCrop';
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot';
  x: number;
  y: number;
  height: number;
  width: number;
};

export type Galerie = {
  _id: string;
  _type: 'galerie';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  ort: OrtReference;
  adresse?: Array<string>;
  link?: string;
  vertretung?: boolean;
  vertretungSeit?: number;
};

export type Ort = {
  _id: string;
  _type: 'ort';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  stadt: string;
  land: string;
  kurztext?: string;
  bild?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: 'image';
  };
  haeuser?: Array<string>;
  reihenfolge?: number;
};

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch';
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: 'sanity.imagePalette';
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions';
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata';
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: 'sanity.fileAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData';
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: 'sanity.imageAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: 'geopoint';
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: 'slug';
  current: string;
  source?: string;
};

export type AllSanitySchemaTypes =
  | Werkstatt
  | Seite
  | Hinweis
  | OrtReference
  | GalerieReference
  | ArchivEintrag
  | SanityImageAssetReference
  | Ausstellung
  | SanityImageCrop
  | SanityImageHotspot
  | Galerie
  | Ort
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint
  | Slug;

// Source: ../src/sanity/queries.ts
// Variable: SEITEN_QUERY
// Query: *[_type == "seite"]{  _id, _type, titel, einleitung, beschreibung}
export type SEITEN_QUERY_RESULT = Array<{
  _id: string;
  _type: 'seite';
  titel: string;
  einleitung: string | null;
  beschreibung: string;
}>;

// Source: ../src/sanity/queries.ts
// Variable: HINWEISE_QUERY
// Query: *[_type == "hinweis"] | order(gueltigVon asc){  _id, _type, text,  "von": gueltigVon,  "bis": gueltigBis}
export type HINWEISE_QUERY_RESULT = Array<{
  _id: string;
  _type: 'hinweis';
  text: string;
  von: string;
  bis: string;
}>;

// Source: ../src/sanity/queries.ts
// Variable: AUSSTELLUNGEN_QUERY
// Query: *[_type == "ausstellung"] | order(start asc){  _id, _type, titel, art, haus, adresse, start, ende, spotlight,  eroeffnung, oeffnungszeiten, oeffnungszeitenBezeichnung, kooperation,  beschreibung,  link { text, url },  "ort": ort->{ _id, _type, stadt, land },  "galerie": galerie->{ _id, _type, name },  hauptbild {  "asset": asset->{ _id, url, "breite": metadata.dimensions.width, "hoehe": metadata.dimensions.height },  alt,  bildunterschrift,  nachweis,  hotspot { x, y, width, height },  crop { top, bottom, left, right }},  bilder[] {  "asset": asset->{ _id, url, "breite": metadata.dimensions.width, "hoehe": metadata.dimensions.height },  alt,  bildunterschrift,  nachweis,  hotspot { x, y, width, height },  crop { top, bottom, left, right }}}
export type AUSSTELLUNGEN_QUERY_RESULT = Array<{
  _id: string;
  _type: 'ausstellung';
  titel: string;
  art: 'galerie' | 'kirche' | 'messe' | 'museum' | 'werkstatt';
  haus: string;
  adresse: Array<string> | null;
  start: string;
  ende: string;
  spotlight: boolean | null;
  eroeffnung: Array<string> | null;
  oeffnungszeiten: Array<string> | null;
  oeffnungszeitenBezeichnung: string | null;
  kooperation: Array<string> | null;
  beschreibung: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal';
    listItem?: never;
    markDefs?: Array<{
      href: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }> | null;
  link: {
    text: string;
    url: string;
  } | null;
  ort: {
    _id: string;
    _type: 'ort';
    stadt: string;
    land: string;
  };
  galerie: {
    _id: string;
    _type: 'galerie';
    name: string;
  } | null;
  hauptbild: {
    asset: {
      _id: string;
      url: string;
      breite: number | null;
      hoehe: number | null;
    } | null;
    alt: string;
    bildunterschrift: string | null;
    nachweis: string;
    hotspot: {
      x: number;
      y: number;
      width: number;
      height: number;
    } | null;
    crop: {
      top: number;
      bottom: number;
      left: number;
      right: number;
    } | null;
  };
  bilder: Array<{
    asset: {
      _id: string;
      url: string;
      breite: number | null;
      hoehe: number | null;
    } | null;
    alt: string;
    bildunterschrift: string | null;
    nachweis: string;
    hotspot: {
      x: number;
      y: number;
      width: number;
      height: number;
    } | null;
    crop: {
      top: number;
      bottom: number;
      left: number;
      right: number;
    } | null;
  }> | null;
}>;

// Source: ../src/sanity/queries.ts
// Variable: ORTE_QUERY
// Query: *[_type == "ort"] | order(reihenfolge asc){  _id, _type, stadt, land, kurztext, reihenfolge, haeuser,  bild {  "asset": asset->{ _id, url, "breite": metadata.dimensions.width, "hoehe": metadata.dimensions.height },  alt,  hotspot { x, y, width, height },  crop { top, bottom, left, right }}}
export type ORTE_QUERY_RESULT = Array<{
  _id: string;
  _type: 'ort';
  stadt: string;
  land: string;
  kurztext: string | null;
  reihenfolge: number | null;
  haeuser: Array<string> | null;
  bild: {
    asset: {
      _id: string;
      url: string;
      breite: number | null;
      hoehe: number | null;
    } | null;
    alt: string;
    hotspot: {
      x: number;
      y: number;
      width: number;
      height: number;
    } | null;
    crop: {
      top: number;
      bottom: number;
      left: number;
      right: number;
    } | null;
  } | null;
}>;

// Source: ../src/sanity/queries.ts
// Variable: ARCHIV_QUERY
// Query: *[_type == "archivEintrag"] | order(jahr desc, reihenfolge asc){  _id, _type, jahr, beginnJahr, reihenfolge, inListe, titel, ortszeile, datum,  link { text, url },  haus,  "ortId": ort._ref,  "galerie": galerie->{ _id, _type, name }}
export type ARCHIV_QUERY_RESULT = Array<{
  _id: string;
  _type: 'archivEintrag';
  jahr: number;
  beginnJahr: number | null;
  reihenfolge: number;
  inListe: boolean | null;
  titel: string | null;
  ortszeile: string | null;
  datum: string | null;
  link: {
    text: string;
    url: string;
  } | null;
  haus: string | null;
  ortId: string | null;
  galerie: {
    _id: string;
    _type: 'galerie';
    name: string;
  } | null;
}>;

// Query TypeMap
declare global {
  interface SanityQueries {
    '*[_type == "seite"]{\n  _id, _type, titel, einleitung, beschreibung\n}': SEITEN_QUERY_RESULT;
    '*[_type == "hinweis"] | order(gueltigVon asc){\n  _id, _type, text,\n  "von": gueltigVon,\n  "bis": gueltigBis\n}': HINWEISE_QUERY_RESULT;
    '*[_type == "ausstellung"] | order(start asc){\n  _id, _type, titel, art, haus, adresse, start, ende, spotlight,\n  eroeffnung, oeffnungszeiten, oeffnungszeitenBezeichnung, kooperation,\n  beschreibung,\n  link { text, url },\n  "ort": ort->{ _id, _type, stadt, land },\n  "galerie": galerie->{ _id, _type, name },\n  hauptbild {\n  "asset": asset->{ _id, url, "breite": metadata.dimensions.width, "hoehe": metadata.dimensions.height },\n  alt,\n  bildunterschrift,\n  nachweis,\n  hotspot { x, y, width, height },\n  crop { top, bottom, left, right }\n},\n  bilder[] {\n  "asset": asset->{ _id, url, "breite": metadata.dimensions.width, "hoehe": metadata.dimensions.height },\n  alt,\n  bildunterschrift,\n  nachweis,\n  hotspot { x, y, width, height },\n  crop { top, bottom, left, right }\n}\n}': AUSSTELLUNGEN_QUERY_RESULT;
    '*[_type == "ort"] | order(reihenfolge asc){\n  _id, _type, stadt, land, kurztext, reihenfolge, haeuser,\n  bild {\n  "asset": asset->{ _id, url, "breite": metadata.dimensions.width, "hoehe": metadata.dimensions.height },\n  alt,\n  hotspot { x, y, width, height },\n  crop { top, bottom, left, right }\n}\n}': ORTE_QUERY_RESULT;
    '*[_type == "archivEintrag"] | order(jahr desc, reihenfolge asc){\n  _id, _type, jahr, beginnJahr, reihenfolge, inListe, titel, ortszeile, datum,\n  link { text, url },\n  haus,\n  "ortId": ort._ref,\n  "galerie": galerie->{ _id, _type, name }\n}': ARCHIV_QUERY_RESULT;
  }
}
// Lets @sanity/client releases that predate the global registry read it too
declare module '@sanity/client' {
  interface SanityQueries extends globalThis.SanityQueries {}
}
